volumes:
    app_data:
        name: almabase_app_data
    static_files:
        name: almabase_static_files
    app_broker:
        name: almabase_app_broker

services:
    django: &django
        build:
            context: .
            dockerfile: Dockerfile
        image: almabase:development
        restart: unless-stopped
        container_name: almabase_django
        command: /app/docker/start.sh server
        env_file:
            - .dev.env
        ports:
            - 8000:8000
        volumes:       
            - .:/app
            - static_files:/app/static:rw

    redis:
        image: redis:6.2.5-alpine
        container_name: almabase_redis
        command: redis-server --appendonly yes
        volumes:
            - app_broker:/var/lib/redis/data
        
        
    
    celery:
        <<: *django
        container_name: almabase_celery
        depends_on:
            - django
            - redis
        ports:
            - 8001:8000
        command: /app/docker/start.sh worker
    
    
    
