volumes:
    app_data:
        name: almabase_app_data
    static_files:
        name: almabase_static_files
    media_files:
        name: almabase_media_files
    certbot_web:
        name: almabase_certbot_web
    certbot_certs:
        name: almabase_certbot_certs
    nginx_config:
        name: almabase_nginx_config

services:
    django:
        build: &django
            context: .
            dockerfile: Dockerfile
        image: almabase:production
        restart: unless-stopped
        container_name: almabase_django_production
        command: /app/docker/start.sh server
        env_file:
            - .prod.env
        ports:
            - 8000:8000
        volumes:
            - static_files:/app/static
            - media_files:/app/media
    
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:production
        container_name: almabase_nginx_production
        ports:
            - 80:80
            - 443:443
        depends_on:
            - django
        volumes:
            - static_files:/app/static:ro
            - media_files:/app/media:ro
            - certbot_web:/vol/www:ro
            - certbot_certs:/etc/letsencrypt/:ro
            - nginx_config:/etc/nginx/:rw
        env_file:
            - .prod.env

    certbot:
        container_name: almabase_certbot_production      
        build:
            context: ./certbot
        depends_on:
            - nginx
        env_file:
            - .prod.env
        volumes:
            - certbot_web:/vol/www:rw
            - certbot_certs:/etc/letsencrypt/:rw
            - nginx_config:/etc/nginx/:rw
        restart: unless-stopped
    
    redis:
        image: redis:6.2.5-alpine
        command: redis-server --appendonly yes
        volumes:
            - app_broker:/var/lib/redis/data
    
    celery:
        <<: *django
        container_name: almabase_celery_production
        depends_on:
            - django
            - redis
        ports:
            - 8001:8000
        command: /app/docker/start.sh worker
