# Generated by Django 2.2.28 on 2024-12-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.URLField()),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('record_capicity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
            ],
        ),
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('customer_type', models.CharField(blank=True, max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.FloatField()),
                ('task_type', models.CharField(blank=True, choices=[('task_01', 'Task 01'), ('task_02', 'Task 02'), ('task_03', 'Task 03'), ('task_04', 'Task 04'), ('task_05', 'Task 05')], max_length=10)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserRecords')),
            ],
        ),
    ]
